---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gsalegig-api
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gsalegig-api
  template:
    metadata:
      labels:
        app: gsalegig-api
    spec:
      containers:
        - name: gsalegig-api-container
          #image: {{ .Values.image.tag }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi