---
apiVersion: v1
kind: Service
metadata:
  name: gsalegig-api-service
spec:
  selector:
    app: gsalegig-api
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
  type: ClusterIP