apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gsalegig-release
  namespace: dev
spec:
  releaseName: gsalegig-api
  targetNamespace: dev
  interval: 1m
  chart:
    spec:
      chart: services/gsalegig-api/helm
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      repository: 450287579526.dkr.ecr.us-west-1.amazonaws.com/dev/gsalegig-api
      tag: 450287579526.dkr.ecr.us-west-1.amazonaws.com/dev/gsalegig-api:20250611172639 # {"$imagepolicy": "flux-system:gsalegig-api"}
    service:
      type: LoadBalancer
      port: 80
