"""Add Items Tables

Revision ID: 1b1f9cbbb965
Revises: 878c6678591b
Create Date: 2025-07-27 12:15:29.757344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1f9cbbb965'
down_revision: Union[str, Sequence[str], None] = '878c6678591b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('NEW', 'ACTIVE', 'INACTIVE', name='userstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
