"""Add Items Tables2

Revision ID: 7684f8378bdf
Revises: 1b1f9cbbb965
Create Date: 2025-07-27 12:29:38.170975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7684f8378bdf'
down_revision: Union[str, Sequence[str], None] = '1b1f9cbbb965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('found_items',
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('desired_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACTIVE', 'INACTIVE', name='founditemstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_found_items_id'), 'found_items', ['id'], unique=False)
    op.create_table('requested_items',
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('desired_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACTIVE', 'INACTIVE', name='requesteditemstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requested_items_id'), 'requested_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requested_items_id'), table_name='requested_items')
    op.drop_table('requested_items')
    op.drop_index(op.f('ix_found_items_id'), table_name='found_items')
    op.drop_table('found_items')
    # ### end Alembic commands ###
