"""and first and last names to users table

Revision ID: 878c6678591b
Revises: 963bd2a4331b
Create Date: 2025-07-25 12:13:54.623932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '878c6678591b'
down_revision: Union[str, Sequence[str], None] = '963bd2a4331b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.alter_column('users', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('name'), table_name='users')
    op.drop_index(op.f('phone_number'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('name'), 'users', ['name'], unique=True)
    op.alter_column('users', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
