---
apiVersion: v1
kind: Service
metadata:
  name: name-generator-app-service
spec:
  selector:
    app: name-generator-webapp
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
  