apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-base
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  path: ./../../environments/dev/monitoring/base
  sourceRef:
    kind: GitRepository
    name: flux-system