apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: name-generator
  namespace: monitoring  # This must match the namespace where Prometheus is deployed
  labels:
    release: prometheus  # Must match .Values.prometheus.serviceMonitorSelector.matchLabels
spec:
  selector:
    matchLabels:
      helm.toolkit.fluxcd.io/name: name-generator-release
      # app: name-generator-app-service
  namespaceSelector:
    matchNames:
      - dev  # Target namespace where the Service lives
  endpoints:
    - port: http
      path: /metrics
      interval: 15s