controller:
  service:
    type: LoadBalancer
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
  extraArgs:
    enable-prometheus-metrics: "true"
    metrics-per-host: "true"
    metrics-per-ingress: "true"