# environments/dev/monitoring/base/grafana-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: 9.2.2  # or latest stable helm chart version
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 5m
  values:
    service:
      type: LoadBalancer
    adminPassword: "admin"  # for demo purposes only
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus-operated.monitoring.svc.cluster.local:9090
            isDefault: true