apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus-repository.yaml
  - prometheus-release.yaml
  - grafana-repository.yaml
  - grafana-release.yaml