apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  install:
    crds: CreateReplace
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 58.0.0   # Match a tested version
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      service:
        type: ClusterIP