name: Build and Push Name Generator to ECR

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:                  # files that the action watches
      - services/name-generator/**

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest     # Use the latest Ubuntu runner

    steps:    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::450287579526:role/github-actions-ecr-push
        role-session-name: github-actions
        aws-region: us-west-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Generate image tag
      shell: bash
      run: echo "IMAGE_TAG=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Generate github sha 
      shell: bash
      run: echo "GITHUB_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: name-generator-ecr
      run: |
        docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.IMAGE_TAG }} services/name-generator/app

#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Run Docker Scout CVE scan
#        uses: docker/scout-action@v1
#        with:
#          command: cves
#          image: $IMAGE_NAME:$IMAGE_TAG
      
    - name: Tag, and push image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: name-generator-ecr
      run: |
        docker tag ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.IMAGE_TAG }} ${ECR_REGISTRY}/${ECR_REPOSITORY}:LATEST
        docker tag ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.IMAGE_TAG }} ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.GITHUB_SHA }}
        docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.IMAGE_TAG }}
        docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.GITHUB_SHA }}
        docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:LATEST
